jobs:
  include:
    - language: python
      python:
        # PyPy versions
        - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
      # command to install dependencies
      install:
        - pip install pytest
      # command to run tests
      script:
        - cd tests
        - pytest
    - language: php
      php:
        - 7.4
      install:
        - sudo apt update
        - sudo apt install mysql-server
      script:
        - /etc/init.d/mysql start
        - sudo systemctl status mysql
        - sudo mysql -u < /home/travis/build/ineelshah/SRIJAS/Code/Database/schema/srijas.sql
        - echo '{"server_name":"127.0.0.1","user_name":"root","password":"","db_name":"srijas"}'>/home/travis/build/ineelshah/SRIJAS/Code/Web_app/parameters.json
        - cd /home/travis/build/ineelshah/SRIJAS/Code/Web_app
        - php test.php
        
